backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "SEO Description", name: "description", required: false, widget: "text"}
      - {label: "Post Author", name: "postauthor", widget: "relation", collection: "authors", valueField: ["slug", "name"], searchFields: ["name"]}
      - {label: "Related Post", name: "relatedPost", widget: "relation", collection: "blog", valueField: "slug", searchFields: ["title"]}

  - name: "authors"
    label: "Authors"
    folder: "_data/authors"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string", hint: "First and Last"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Avatar", name: avatar, widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/company/index.md"
        label: "Company"
        name: "company"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "company-template"}
          - {label: Hero, name: hero, widget: object, fields: [{label: Title, name: heroTitle, widget: string}, {label: Description, name: heroDescription, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: "Team", name: team, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Members, name: members, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: "Values", name: values, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}


      - file: "src/pages/technologies/index.md"
        label: "Technologies"
        name: "technologies"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "technology-template"}
          - {label: Hero, name: hero, widget: object, fields: [{label: Title, name: heroTitle, widget: string}, {label: Description, name: heroDescription, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: "Platforms", name: platforms, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: "Development Practices", name: practices, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: "Technologies", name: technologies, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}
      
      - file: "src/pages/batuwa/index.md"
        label: "Batuwa"
        name: "batuwa"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "batuwa-template"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-template"}
          - {label: Hero, name: hero, widget: object, fields: [{label: Title, name: heroTitle, widget: string}, {label: Description, name: heroDescription, widget: text}, {label: Image, name: image, widget: image}]}
          - {label: "What", name: whatWeDo, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Sub Heading, name: subHeading, widget: string}, {label: Description heading, name: descHeading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: How, name: howWeWork, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Sub Heading, name: subHeading, widget: string}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: "Process", name: process, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: Clients, name: clients, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Sub Heading, name: subHeading, widget: string}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Heading, name: heading, widget: text}, {label: Text, name: text, widget: text}]}]}