backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/company/content/index.md"
        label: "Company"
        name: "company"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "company-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/technologies/content/index.md"
        label: "Technologies"
        name: "technologies"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "technology-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      
      - file: "src/pages/clientele/content/index.md"
        label: "Clientele"
        name: "clientele"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "clientele-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}